import dotenv from "dotenv";

dotenv.config({ quiet: true });

export const env = {
  PORT: process.env.PORT || 4000,
  DATABASE_URL: process.env.DATABASE_URL,
  JWT_SECRET: process.env.JWT_SECRET,
  DEEPSEEK_API_KEY: process.env.DEEPSEEK_API_KEY,
  DEEPSEEK_BASE_URL: process.env.DEEPSEEK_BASE_URL || "https://api.deepseek.com",
  DEEPSEEK_MODEL: process.env.DEEPSEEK_MODEL || "deepseek-v4-flash",
  DEEPSEEK_MODE: process.env.DEEPSEEK_MODE || "hemat",
  DEEPSEEK_TIMEOUT_MS: Number(process.env.DEEPSEEK_TIMEOUT_MS || 15000),
  DEEPSEEK_MAX_RETRIES: Number(process.env.DEEPSEEK_MAX_RETRIES || 1),
  DEEPSEEK_TEMPERATURE: Number(process.env.DEEPSEEK_TEMPERATURE || 0.2),
  DEEPSEEK_MAX_OUTPUT_TOKENS: Number(process.env.DEEPSEEK_MAX_OUTPUT_TOKENS || 700),
  DEEPSEEK_HEMAT_TIMEOUT_MS: Number(process.env.DEEPSEEK_HEMAT_TIMEOUT_MS || 12000),
  DEEPSEEK_HEMAT_MAX_RETRIES: Number(process.env.DEEPSEEK_HEMAT_MAX_RETRIES || 0),
  DEEPSEEK_HEMAT_TEMPERATURE: Number(process.env.DEEPSEEK_HEMAT_TEMPERATURE || 0.15),
  DEEPSEEK_HEMAT_MAX_OUTPUT_TOKENS: Number(process.env.DEEPSEEK_HEMAT_MAX_OUTPUT_TOKENS || 450),
  DEEPSEEK_NORMAL_TIMEOUT_MS: Number(process.env.DEEPSEEK_NORMAL_TIMEOUT_MS || 15000),
  DEEPSEEK_NORMAL_MAX_RETRIES: Number(process.env.DEEPSEEK_NORMAL_MAX_RETRIES || 1),
  DEEPSEEK_NORMAL_TEMPERATURE: Number(process.env.DEEPSEEK_NORMAL_TEMPERATURE || 0.25),
  DEEPSEEK_NORMAL_MAX_OUTPUT_TOKENS: Number(process.env.DEEPSEEK_NORMAL_MAX_OUTPUT_TOKENS || 850),
  DEEPSEEK_THINKING: process.env.DEEPSEEK_THINKING || "disabled",
  GEMINI_API_KEY: process.env.GEMINI_API_KEY,
  GEMINI_MODEL: process.env.GEMINI_MODEL || "gemini-2.0-flash",
  GEMINI_VISION_MODEL: process.env.GEMINI_VISION_MODEL || process.env.GEMINI_MODEL || "gemini-2.0-flash",
  GEMINI_EMBEDDING_MODEL: process.env.GEMINI_EMBEDDING_MODEL || "gemini-embedding-001",
  GEMINI_EMBEDDING_DIM: Number(process.env.GEMINI_EMBEDDING_DIM || 768),
  GEMINI_TIMEOUT_MS: Number(process.env.GEMINI_TIMEOUT_MS || 15000),
  GEMINI_MAX_RETRIES: Number(process.env.GEMINI_MAX_RETRIES || 1),
  GEMINI_TEMPERATURE: Number(process.env.GEMINI_TEMPERATURE || 0.2),
  GEMINI_MAX_OUTPUT_TOKENS: Number(process.env.GEMINI_MAX_OUTPUT_TOKENS || 700),
  GEMINI_SAFETY_THRESHOLD: process.env.GEMINI_SAFETY_THRESHOLD || "BLOCK_MEDIUM_AND_ABOVE",
  RAG_MODE: process.env.RAG_MODE || "keyword",
  RAG_MIN_SIMILARITY: Number(process.env.RAG_MIN_SIMILARITY || 0.25),
  AI_MIN_RESPONSE_MS: Number(process.env.AI_MIN_RESPONSE_MS || 900),
  SMTP_HOST: process.env.SMTP_HOST,
  SMTP_PORT: Number(process.env.SMTP_PORT || 1025),
  SMTP_USER: process.env.SMTP_USER,
  SMTP_PASS: process.env.SMTP_PASS,
  SMTP_FROM: process.env.SMTP_FROM || "helpdesk@epson.local",
  MAILPIT_WEB_URL: process.env.MAILPIT_WEB_URL || "http://localhost:8025",
  CORS_ORIGIN: process.env.CORS_ORIGIN,
};
